name: myapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  multiselect: ^0.0.7
  image_picker: ^0.8.4+2
  video_player: ^2.2.5
  chewie: ^1.2.0
  file_picker: ^5.2.10



    



  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  multiselect_dropdown_flutter: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  
  assets:
      - assets/
 

 
  